name: Deploy
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Run Web App
    runs-on: self-hosted
    steps:
      - name: Build Web App
        run: |
          echo "Build Web App"
          
      - uses: convictional/trigger-workflow-and-wait@v1.3.0
        with:
          owner: pavankarnax
          repo: caller
          github_token: ${{ secrets.G_ACCESS_TOKEN }}
          workflow_file_name: main.yml
          ref: main
      - name: Deploy Web App
        run: |
          echo "Deploy Web App"
          sleep 10s
